### ISSUE TITLE
upload_tmp_dir (setting in php.ini) to allow php to upload files

### ISSUE THREAD

**Issue by surphil** [blunix/role-php-fpm#25]
Next to issue #22 we also need "upload_tmp_dir" (setting in php.ini) to allow php to upload files. I think the path must exists with right permissions.

**Comment by p-thurner** [comment]
@surphil you can set any desired php.ini settings in your play like so: https://github.com/blunix/role-php-fpm/blob/1.0.7/molecule/default/playbook.yml#L13-L29

(closing this issue as the role already implements that feature)
